version: 1
paths:
  pool: /mnt/pool/media
  scratch: /mnt/scratch
  appdata: /home/ethan/eznas/app
services:
  qbittorrent:
    enabled: true
    port: 8081
    proxy_url: null
    stop_after_download: true
    username: admin
    password: ''
  radarr:
    enabled: true
    port: 7878
    proxy_url: null
  sonarr:
    enabled: true
    port: 8989
    proxy_url: null
  prowlarr:
    enabled: true
    port: 9696
    proxy_url: null
    language_filter: true
  jellyseerr:
    enabled: true
    port: 5055
    proxy_url: null
  jellyfin:
    enabled: true
    port: 8096
    proxy_url: null
  bazarr:
    enabled: true
    port: 6767
    proxy_url: null
  flaresolverr:
    enabled: true
    port: 8191
    proxy_url: null
  pipeline:
    enabled: true
    port: null
    proxy_url: null
  gluetun:
    enabled: true
    port: null
    proxy_url: null
    wireguard_config: '[Interface]

      # Key for ghoul

      # Bouncing = 18

      # NetShield = 2

      # Moderate NAT = off

      # NAT-PMP (Port Forwarding) = off

      # VPN Accelerator = on

      PrivateKey = CNehVcNBy+1RmeNcPgXJNUGxBJO838786GVaoBXaHG4=

      Address = 10.2.0.2/32, 2a07:b944::2:2/128

      DNS = 10.2.0.1, 2a07:b944::2:1


      [Peer]

      # CH#696

      PublicKey = 36G8+pInNcPK9F1TpHglWs9Pk5uJOY9o8SCNrCBgvHE=

      AllowedIPs = 0.0.0.0/0, ::/0

      Endpoint = 89.222.96.158:51820


      # Uncomment the following line (delete the # symbol) to connect to Proton VPN
      using IPv6.

      # Endpoint = [2a02:6ea0:d411:6002::10]:51820

      PersistentKeepalive = 25'
proxy:
  enabled: false
  image: traefik:v3.1
  http_port: 80
  https_port: null
  dashboard: false
  additional_args: []
download_policy:
  categories:
    radarr: movies
    sonarr: tv
media_policy:
  movies:
    keep_audio:
    - eng
    - und
    keep_subs:
    - eng
quality:
  preset: balanced
  target_resolution: null
  max_bitrate_mbps: null
  preferred_container: mkv
ui:
  port: 8443
runtime:
  user_id: 1000
  group_id: 1000
  timezone: UTC
users: []
