version: 1
paths:
  pool: /home/ethan/eznas/test_pool
  scratch: /home/ethan/eznas/test_scratch
  appdata: /home/ethan/eznas/test_appdata
services:
  qbittorrent:
    enabled: true
    port: 8080
    proxy_url: null
    stop_after_download: true
    username: admin
    password: adminadmin
  radarr:
    enabled: true
    port: 7878
    proxy_url: null
  sonarr:
    enabled: true
    port: 8989
    proxy_url: null
  prowlarr:
    enabled: true
    port: 9696
    proxy_url: null
  jellyseerr:
    enabled: true
    port: 5055
    proxy_url: null
  jellyfin:
    enabled: true
    port: 8096
    proxy_url: null
  pipeline:
    enabled: true
    port: null
    proxy_url: null
download_policy:
  categories:
    radarr: movies
    sonarr: tv
    anime: anime
media_policy:
  movies:
    keep_audio:
    - eng
    - und
    keep_subs:
    - eng
    - forced
  anime:
    keep_audio:
    - jpn
    - eng
    - und
    keep_subs:
    - eng
quality:
  preset: balanced
ui:
  port: 8443
runtime:
  user_id: 1000
  group_id: 1000
  timezone: UTC
users:
- username: admin
  email: admin@example.com
  role: owner
